on:
  pull_request:
    types: [opened, synchronize]

name: Static check with PR and Add comment each error

jobs:
  fmt:
    name: gofmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run gofmt
      uses: ./.github/actions/static-check-action
      env:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
      with:
        run: fmt

  imports:
    name: goimports
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run goimports
      uses: ./.github/actions/static-check-action
      with:
        run: imports
        repo-token: ${{ secrets.GITHUB_TOKEN }}
  
  lint:
    name: golint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run golint
      uses: ./.github/actions/static-check-action
      env:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
      with:
        run: lint
 
  gsc:
    name: gsc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run gsc
      uses: ./.github/actions/static-check-action
      env:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
      with:
        run: gsc
 
  sec:
    name: sec
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run gosec
      uses: ./.github/actions/static-check-action
      env:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
      with:
        run: sec
        
  staticcheck:
    name: staticcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run staticcheck
      uses: ./.github/actions/static-check-action
      env:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
      with:
        run: staticcheck

